[project]
name = "medicine-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "image>=1.5.33",
    "selenium>=4.29.0",
    "streamlit>=1.43.2",
    "webdriver-manager>=4.0.2",
]
